# agentflow/codegen_langgraph.py
#
# Generates LangGraph-style Python from an IR program. The generated
# code is a faithful translation: one node function per state, one
# router function per conditional branch, and a build_graph() that
# wires them together with add_node / add_edge / add_conditional_edges.
#
# The output is validated with ast.parse() and compile() after
# generation -- it is never executed by the compiler itself (LangGraph
# is not a dependency of this project; the interpreter backend is what
# actually runs the IR).

import ast as _ast

from .errors import IRError
from .ast_nodes import ToolDeclNode, AgentDeclNode


class LangGraphCodegen:
    def __init__(self):
        self.out = []
        self.indent = 0
        self.ast = None
        self.ir = None
        self.tools = {}
        self.agents = {}
        self.blocks = {}

    # ---- public ----

    def generate(self, ast, ir, source_name="<unknown>"):
        self.out = []
        self.indent = 0
        self.ast = ast
        self.ir = ir

        self.tools = {}
        self.agents = {}
        for decl in ast.decls:
            if isinstance(decl, ToolDeclNode):
                self.tools[decl.name] = decl
            elif isinstance(decl, AgentDeclNode):
                self.agents[decl.name] = decl

        self.blocks = self._compute_blocks(ir)

        self._header(source_name)
        self._imports()
        self._tool_stubs()
        self._agent_functions()
        self._state_functions()
        self._routers()
        self._build_graph()

        text = "\n".join(self.out) + "\n"

        # Validate the generated Python parses.
        try:
            _ast.parse(text)
        except SyntaxError as e:
            raise IRError("generated code failed ast.parse: %s" % e)
        try:
            compile(text, "<generated>", "exec")
        except SyntaxError as e:
            raise IRError("generated code failed compile(): %s" % e)

        return text

    # ---- emit helpers ----

    def _line(self, s=""):
        self.out.append("    " * self.indent + s)

    def _blank(self):
        self.out.append("")

    # ---- blocks ----

    def _compute_blocks(self, ir):
        sorted_labels = sorted(ir.labels.items(), key=lambda kv: kv[1])
        blocks = {}
        for i, (label, start) in enumerate(sorted_labels):
            end = (
                sorted_labels[i + 1][1]
                if i + 1 < len(sorted_labels)
                else len(ir.instructions)
            )
            blocks[label] = (start, end)
        return blocks

    # ---- sections ----

    def _header(self, source_name):
        self._line("# Auto-generated by AgentFlow from %s" % self.ast.name)
        self._line("# Source: %s" % source_name)
        self._line("# Do not edit; regenerate from the .aflow file.")
        self._blank()

    def _imports(self):
        self._line("from langgraph.graph import StateGraph, END")
        self._blank()
        self._blank()

    def _tool_stubs(self):
        self._line(
            "# ---- tools -------------------------------------------------------"
        )
        self._blank()
        for name, decl in self.tools.items():
            params = ", ".join(p[0] for p in decl.params)
            sig = ", ".join("%s: %s" % p for p in decl.params)
            self._line("def %s(%s):" % (name, params))
            self.indent += 1
            self._line('"""tool %s(%s) -> %s"""' % (name, sig, decl.return_type))
            self._line('raise NotImplementedError("mock tool: %s")' % name)
            self.indent -= 1
            self._blank()
        self._blank()

    def _agent_functions(self):
        self._line(
            "# ---- agents ------------------------------------------------------"
        )
        self._blank()
        for name, decl in self.agents.items():
            tool = self.tools.get(decl.tool_name)
            self._line("def %s(state, *args):" % name)
            self.indent += 1
            self._line('"""agent %s uses %s"""' % (name, decl.tool_name))
            self._line("if args:")
            self.indent += 1
            self._line("return %s(*args)" % decl.tool_name)
            self.indent -= 1
            if tool is not None and tool.params:
                params = ", ".join('state.get("%s")' % p[0] for p in tool.params)
                self._line("return %s(%s)" % (decl.tool_name, params))
            else:
                self._line("return %s()" % decl.tool_name)
            self.indent -= 1
            self._blank()
        self._blank()

    def _state_functions(self):
        self._line(
            "# ---- state functions ---------------------------------------------"
        )
        self._blank()
        for label in self.blocks:
            self._emit_state_function(label)
        self._blank()

    def _emit_state_function(self, label):
        start, end = self.blocks[label]
        self._line("def state_%s(state):" % label)
        self.indent += 1
        self._line("out = dict(state)")
        for idx in range(start, end):
            instr = self.ir.instructions[idx]
            if instr.op in ("ENTER", "JUMP", "BRANCH", "HALT"):
                continue
            self._emit_instr(instr)
        self._line("return out")
        self.indent -= 1
        self._blank()

    def _emit_instr(self, instr):
        if instr.op == "ASSIGN":
            dst, src = instr.args
            self._line('out["%s"] = %s' % (dst, self._operand_to_py(src)))
        elif instr.op in ("ADD", "SUB", "MUL", "DIV"):
            dst, a, b = instr.args
            py_op = {"ADD": "+", "SUB": "-", "MUL": "*", "DIV": "//"}[instr.op]
            self._line(
                'out["%s"] = %s %s %s'
                % (dst, self._operand_to_py(a), py_op, self._operand_to_py(b))
            )
        elif instr.op == "CALL":
            dst, agent_name, arg_names = instr.args
            arg_exprs = ", ".join(self._operand_to_py(a) for a in arg_names)
            if arg_exprs:
                call = "%s(out, %s)" % (agent_name, arg_exprs)
            else:
                call = "%s(out)" % agent_name
            if dst is not None:
                self._line('out["%s"] = %s' % (dst, call))
            else:
                self._line(call)

    def _operand_to_py(self, op):
        if op is None:
            return "None"
        s = str(op)
        try:
            int(s)
            return s
        except ValueError:
            pass
        if len(s) >= 2 and s[0] == '"' and s[-1] == '"':
            return s
        return 'out["%s"]' % s

    def _routers(self):
        self._line(
            "# ---- routers -----------------------------------------------------"
        )
        self._blank()
        for label in self.blocks:
            start, end = self.blocks[label]
            last = self.ir.instructions[end - 1] if end > start else None
            if last is None or last.op != "BRANCH":
                continue
            cond, true_target, false_target = last.args
            true_name = true_target if true_target is not None else "END"
            false_name = false_target if false_target is not None else "END"
            self._line("def route_%s(state):" % label)
            self.indent += 1
            self._line(
                'return "%s" if state.get("%s") else "%s"'
                % (true_name, cond, false_name)
            )
            self.indent -= 1
            self._blank()
        self._blank()

    def _build_graph(self):
        self._line(
            "# ---- graph -------------------------------------------------------"
        )
        self._blank()
        self._line("def build_graph():")
        self.indent += 1
        self._line("graph = StateGraph(dict)")

        for label in self.blocks:
            self._line('graph.add_node("%s", state_%s)' % (label, label))

        self._line('graph.set_entry_point("%s")' % self.ir.entry)

        for label in self.blocks:
            start, end = self.blocks[label]
            last = self.ir.instructions[end - 1] if end > start else None
            if last is None:
                continue
            if last.op == "JUMP":
                self._line('graph.add_edge("%s", "%s")' % (label, last.args[0]))
            elif last.op == "BRANCH":
                cond, t, f = last.args
                t_name = t if t is not None else "END"
                f_name = f if f is not None else "END"
                self._line(
                    'graph.add_conditional_edges("%s", route_%s, '
                    '{"%s": "%s", "%s": "%s"})'
                    % (label, label, t_name, t_name, f_name, f_name)
                )
            elif last.op == "HALT":
                self._line('graph.add_edge("%s", END)' % label)

        self._line("return graph.compile()")
        self.indent -= 1
        self._blank()
        self._blank()
        self._line("app = build_graph()")
