# Auto-generated by AgentFlow from OrderProcessor
# Source: examples/order_processor.aflow
# Do not edit; regenerate from the .aflow file.

from langgraph.graph import StateGraph, END


# ---- tools -------------------------------------------------------

def CheckInventory(sku):
    """tool CheckInventory(sku: string) -> bool"""
    raise NotImplementedError("mock tool: CheckInventory")

def ChargeCard(amount):
    """tool ChargeCard(amount: number) -> bool"""
    raise NotImplementedError("mock tool: ChargeCard")

def SendEmail(to):
    """tool SendEmail(to: string) -> void"""
    raise NotImplementedError("mock tool: SendEmail")


# ---- agents ------------------------------------------------------

def InventoryAgent(state, *args):
    """agent InventoryAgent uses CheckInventory"""
    if args:
        return CheckInventory(*args)
    return CheckInventory(state.get("sku"))

def PaymentAgent(state, *args):
    """agent PaymentAgent uses ChargeCard"""
    if args:
        return ChargeCard(*args)
    return ChargeCard(state.get("amount"))

def NotifierAgent(state, *args):
    """agent NotifierAgent uses SendEmail"""
    if args:
        return SendEmail(*args)
    return SendEmail(state.get("to"))


# ---- state functions ---------------------------------------------

def state_Start(state):
    out = dict(state)
    return out

def state_CheckStock(state):
    out = dict(state)
    out["t1"] = InventoryAgent(out)
    return out

def state_Charge(state):
    out = dict(state)
    out["t2"] = 5
    out["fee"] = out["t2"]
    out["total"] = 100
    out["result"] = PaymentAgent(out, out["total"])
    return out

def state_Notify(state):
    out = dict(state)
    out["t3"] = NotifierAgent(out)
    return out

def state_Done(state):
    out = dict(state)
    return out


# ---- routers -----------------------------------------------------

def route_CheckStock(state):
    return "Charge" if state.get("t1") else "Done"

def route_Charge(state):
    return "Notify" if state.get("result") else "Done"


# ---- graph -------------------------------------------------------

def build_graph():
    graph = StateGraph(dict)
    graph.add_node("Start", state_Start)
    graph.add_node("CheckStock", state_CheckStock)
    graph.add_node("Charge", state_Charge)
    graph.add_node("Notify", state_Notify)
    graph.add_node("Done", state_Done)
    graph.set_entry_point("Start")
    graph.add_edge("Start", "CheckStock")
    graph.add_conditional_edges("CheckStock", route_CheckStock, {"Charge": "Charge", "Done": "Done"})
    graph.add_conditional_edges("Charge", route_Charge, {"Notify": "Notify", "Done": "Done"})
    graph.add_edge("Notify", "Done")
    graph.add_edge("Done", END)
    return graph.compile()


app = build_graph()
